id: PABC9AE7B
initial_creation_type: input
source_metadata:
  title: Nyingma Series
  language: fr
  description: 'Texts related to the Nyingma School of Ancient Translations (snga
    ''gyur rnying ma), the oldest tradition within Tibetan Buddhism:'
  volume:
    992c99e2af2f4772a692a97601aba0bf:
      title: 'The Jewelled Garland: An Aspiration for the Spread of the Teachings
        of the Omniscient Father and Son, Masters of the Teachings of the Ancient
        Translations'
      parent: Aspiration Prayers
    d3fded12641545d79980712a3bea4237:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Aspiration Prayers
    33abda61c09142c98201fae4ef1cc40b:
      title: 'A Stream of Blessing: Verses of Supplication to the Accomplished Holders
        of Mantra who Gained Realization in this Snowy Land of Tibet'
      parent: Lineage Prayers
    184166ca97e74cee978baabb155d2f9c:
      title: A Brief Presentation of the Nine Vehicles
      parent: Philosophy
created_at: '2022-03-01T04:53:23.335022'
last_modified_at: '2022-03-01T04:53:23.335025'
